---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    author: alex
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
            value: hbc
        - name: POSTGRES_DB
          value: mybd
        - name: POSTGRES_USER
          value: myuser
...





